### model
model_name_or_path: /data2/wuzhuoyang/study-from-wrong/model/qwen2.5-3b-instruct/Qwen/Qwen2.5-3B-Instruct
trust_remote_code: true

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  

### dataset
dataset: draft_prefs_dpo
template: qwen
cutoff_len: 2048
# max_samples: 9000        
overwrite_cache: true
preprocessing_num_workers: 4
dataloader_num_workers: 4

### output
output_dir: saves/qwen2_5vl-7b/lora/dpo
logging_steps: 20
save_steps: 150          
plot_loss: true
overwrite_output_dir: true
save_only_model: false     
report_to: none

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8  
learning_rate: 1.0e-5            
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

## eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 150         



# pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

# report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]
